# Generated by Django 4.0.4 on 2022-05-03 14:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=28)),
                ('last_name', models.CharField(max_length=28)),
                ('email', models.EmailField(max_length=28)),
                ('compagny', models.CharField(max_length=28)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now_add=True)),
                ('prospect', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contrat_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=28)),
                ('amount', models.IntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_signature', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('nonsigne', 'Non signé'), ('signe', 'Signé')], default='nonsigne', max_length=28)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.client')),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=28)),
                ('type', models.CharField(choices=[('anniversaire', 'Anniversaire'), ('mariage', 'Mariage'), ('nouvelan', 'Nouvel an')], default='anniversaire', max_length=28)),
                ('description', models.CharField(max_length=28)),
                ('localisation', models.IntegerField()),
                ('date_event_begin', models.DateTimeField()),
                ('date_event_end', models.DateTimeField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.contract', verbose_name='client contract')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
