# Generated by Django 4.0.4 on 2022-05-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customemployee',
            name='first_name',
            field=models.CharField(max_length=28),
        ),
    ]
