# Generated by Django 4.0.4 on 2022-05-06 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_client_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': (('can_modified_data_client', 'can modified data client'),)},
        ),
    ]
