# Generated by Django 4.0.4 on 2022-05-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=28)),
                ('amount', models.IntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_signature', models.DateTimeField()),
                ('status', models.CharField(choices=[('nonsigne', 'Non signé'), ('signe', 'Signé')], default='nonsigne', max_length=28)),
            ],
        ),
    ]
