# Generated by Django 4.0.4 on 2022-05-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_signature',
            field=models.DateTimeField(blank=True),
        ),
    ]
