# Generated by Django 4.0.4 on 2022-05-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_customemployee_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='description',
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='localisation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='title',
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
    ]
