# Generated by Django 4.0.4 on 2022-05-07 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_client_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('first_name', 'last_name')},
        ),
    ]
