# Generated by Django 4.0.4 on 2022-05-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_contract_date_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_signature',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
