# Generated by Django 4.0.4 on 2022-05-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_evenement_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='date_event_begin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='date_event_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
