# Generated by Django 4.0.4 on 2022-05-04 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_evenement_date_event_begin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1000)]),
        ),
    ]
