# Generated by Django 4.0.4 on 2022-05-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_contract_date_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=28)),
                ('type', models.CharField(max_length=28)),
                ('description', models.CharField(max_length=28)),
                ('localisation', models.IntegerField()),
                ('date_event_begin', models.DateTimeField(blank=True, null=True)),
                ('date_event_end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
