# Generated by Django 4.0.4 on 2022-05-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_contract_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='localisation',
        ),
        migrations.AddField(
            model_name='evenement',
            name='ville',
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
    ]
