# Generated by Django 4.0.4 on 2022-05-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_evenement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='type',
            field=models.CharField(choices=[('anniversaire', 'Anniversaire'), ('mariage', 'Mariage'), ('nouvelan', 'Nouvel an')], default='anniversaire', max_length=28),
        ),
    ]
