# Generated by Django 4.0.4 on 2022-05-05 14:22

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_contract_date_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='date_event_begin',
            field=models.DateTimeField(blank=True, null=True, validators=[myapp.models.VV_check]),
        ),
    ]
