# Generated by Django 4.0.4 on 2022-05-03 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_contract_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.evenement'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personnel_assignee', to=settings.AUTH_USER_MODEL),
        ),
    ]
