# Generated by Django 4.0.4 on 2022-05-05 14:35

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_evenement_date_event_begin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='date_event_end',
            field=models.DateTimeField(blank=True, null=True, validators=[myapp.models.VV_check]),
        ),
    ]
