# Generated by Django 4.0.4 on 2022-05-03 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_evenement_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_assignee', to=settings.AUTH_USER_MODEL, verbose_name='WOWYWOWY!!!'),
        ),
    ]
