# Generated by Django 4.0.4 on 2022-05-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_evenement_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='date_event_begin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='date_event_end',
            field=models.DateTimeField(),
        ),
    ]
