# Generated by Django 4.0.4 on 2022-05-03 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_evenement_date_event_begin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='event',
        ),
        migrations.AddField(
            model_name='evenement',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.contract'),
        ),
    ]
